# Generated by Django 5.2.15 on 2026-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Từ vựng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
